version: '1'
services:
  db:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: masongzhi
    ports:
      - "27017:27017"
    volumes:
      - ./docker/data/db:/data/db # 挂载数据目录
      - ./docker/data/log:/var/log/mongodb  # 挂载日志目录
      - ./docker/data/config:/etc/mongo  # 挂载配置目录
  redis:
    image: redis
    container_name: redis
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6380:6379"
  web:
    image: node:14
    container_name: node
    depends_on:
      - db
      - redis
    ports:
      - "4000:4000"
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: masongzhi
      MONGO_HOST: db
      MONGO_PORT: 27017
    working_dir: /code
    volumes:
      - .:/code
    command: npm run dev
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf